# --- Required options --- #

# # Name of website
# title: MORED

# # Your name to show in the footer
# author: TICLab, International University of Rabat

# # --- List of links in the navigation bar --- #

# navbar-links:
#   About Me: "aboutme"
#   Resources:
#   Author's home: "https://moredataset.github.io/MORED/"

# theme: jekyll-theme-cayman

theme: jekyll-theme-minimal
image: /Header1.jpg
